"use strict";
const DATA_URL="./data/dashboard-data.json",REFRESH_MS=300000,EXPORT_PASSWORD_HASH="cd08fd629edf86b440567a78e34558009e708d619c966e2c9446bc07c45f2c96";
const state={rows:[],locations:[],page:1,pageSize:50,sortKey:"part",sortDir:1,multiParts:null,sIndex:-1,mIndex:-1};
const $=id=>document.getElementById(id),txt=v=>String(v??"").trim(),num=v=>Number.isFinite(Number(v))?Number(v):0,norm=v=>txt(v).toLowerCase().replace(/\s+/g," ");
localStorage.removeItem('search'); localStorage.removeItem('searchValue'); localStorage.removeItem('stockSearch'); sessionStorage.removeItem('search'); sessionStorage.removeItem('searchValue');const E={search:$("searchInput"),suggest:$("suggestions"),multi:$("multiInput"),multiSuggest:$("multiSuggestions"),multiSummary:$("multiSummary"),head:$("tableHead"),body:$("tableBody"),sync:$("syncStatus"),updated:$("lastUpdated"),exportMenu:$("exportMenu"),exportPw:$("exportPassword"),exportStatus:$("exportStatus")};
function aggregate(stock){const m=new Map();for(const x of stock){const part=txt(x.PartNumber??x.part),desc=txt(x.Description??x.desc),loc=txt(x.Location??x.location),qty=num(x.AvailableQty??x.qty);if(!part||!loc)continue;const k=part.toUpperCase();if(!m.has(k))m.set(k,{part,desc,quantities:{},total:0});const r=m.get(k);if(!r.desc&&desc)r.desc=desc;r.quantities[loc]=num(r.quantities[loc])+qty;r.total+=qty}return[...m.values()]}
async function loadData(manual=false){E.sync.textContent=manual?"Refreshing…":"Loading stock…";try{const r=await fetch(`${DATA_URL}?v=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw Error(`HTTP ${r.status}`);const p=await r.json();state.locations=(p.locations||[]).map(txt);state.rows=aggregate(p.stock||[]);state.page=1;E.updated.textContent=`Last updated: ${txt(p.lastUpdated)||"—"}`;E.sync.textContent="Latest stock loaded";render()}catch(e){console.error(e);E.sync.textContent=state.rows.length?"Refresh failed · showing loaded data":"Could not load stock data"}}
function parseParts(value) {
return [...new Set(
String(value || "")
.split(/[\n\r,;\t]+/)
.map(part => norm(part))
.filter(Boolean)
)];
}
function baseFiltered(){const q=norm(E.search.value);return state.rows.filter(r=>(!q||norm(r.part).includes(q)||norm(r.desc).includes(q))&&(!state.multiParts||state.multiParts.has(norm(r.part))))}
function visibleLocations(rows){return state.locations.filter(loc=>rows.some(r=>num(r.quantities[loc])>0))}
function filtered(){const rows=baseFiltered(),key=state.sortKey,dir=state.sortDir;rows.sort((a,b)=>{let av,bv;if(key==="part"){av=a.part;bv=b.part}else if(key==="desc"){av=a.desc;bv=b.desc}else if(key==="total"){av=a.total;bv=b.total}else{av=num(a.quantities[key]);bv=num(b.quantities[key])}return typeof av==="number"?(av-bv)*dir:txt(av).localeCompare(txt(bv),undefined,{numeric:true,sensitivity:"base"})*dir});return rows}
function arrow(k){return state.sortKey===k?(state.sortDir===1?" ▲":" ▼"):""}function sortBy(k){state.sortKey===k?state.sortDir*=-1:(state.sortKey=k,state.sortDir=1);state.page=1;render()}
function render(){const rows=filtered(),locs=visibleLocations(rows),pages=Math.max(1,Math.ceil(rows.length/state.pageSize));state.page=Math.min(state.page,pages);E.head.innerHTML="";const tr=document.createElement("tr");[["part","Part Number"],["desc","Description"],...locs.map(l=>[l,l]),["total","Total"]].forEach(([k,l])=>{const th=document.createElement("th");th.textContent=l+arrow(k);if(k!=="part"&&k!=="desc")th.className="numeric";th.onclick=()=>sortBy(k);tr.appendChild(th)});E.head.appendChild(tr);E.body.innerHTML="";const pageRows=rows.slice((state.page-1)*state.pageSize,state.page*state.pageSize);if(!pageRows.length){const r=document.createElement("tr");r.className="empty";const d=document.createElement("td");d.colSpan=locs.length+3;d.textContent="No matching stock found.";r.appendChild(d);E.body.appendChild(r)}pageRows.forEach(r=>{const row=document.createElement("tr"),vals=[r.part,r.desc,...locs.map(l=>num(r.quantities[l])),r.total];vals.forEach((v,i)=>{const d=document.createElement("td");if(i>=2){d.textContent=num(v).toLocaleString("en-IN");d.classList.add("numeric")}else d.textContent=txt(v);if(i===vals.length-1)d.classList.add("total");row.appendChild(d)});E.body.appendChild(row)});$("partCount").textContent=rows.length.toLocaleString("en-IN");$("locationCount").textContent=locs.length;$("totalQty").textContent=rows.reduce((s,r)=>s+r.total,0).toLocaleString("en-IN");$("pageStat").textContent=`${rows.length?state.page:0} / ${rows.length?pages:0}`;$("pageInfo").textContent=`Page ${rows.length?state.page:0} of ${rows.length?pages:0}`;$("resultText").textContent=`Showing ${pageRows.length} of ${rows.length} matching parts · only locations with stock are displayed`;$("prevPage").disabled=state.page<=1||!rows.length;$("nextPage").disabled=state.page>=pages||!rows.length;updateSingleSuggestions();updateMultiSuggestions()}
function matches(q){q=norm(q);return q?state.rows.filter(r=>norm(r.part).includes(q)||norm(r.desc).includes(q)):[]}
function fillSuggestions(box,list,select,index){box.innerHTML="";if(!list.length){box.hidden=true;return}list.forEach((r,i)=>{const d=document.createElement("div");d.className="suggestion"+(i===index?" active":"");d.innerHTML="";const a=document.createElement("strong"),b=document.createElement("span");a.textContent=r.part;b.textContent=r.desc||"No description";d.append(a,b);d.onmousedown=e=>{e.preventDefault();select(i)};box.appendChild(d)});box.hidden=false}
function updateSingleSuggestions(){fillSuggestions(E.suggest,matches(E.search.value),i=>{const m=matches(E.search.value)[i];if(m)E.search.value=m.part;E.suggest.hidden=true;state.page=1;render()},state.sIndex)}
function currentMultiToken(){const v=E.multi.value;return txt(v.slice(Math.max(v.lastIndexOf(","),v.lastIndexOf(";"),v.lastIndexOf("\n"))+1))}
function updateMultiSuggestions(){fillSuggestions(E.multiSuggest,matches(currentMultiToken()),selectMulti,state.mIndex)}
function selectMulti(i){const m=matches(currentMultiToken())[i];if(!m)return;const v=E.multi.value,cut=Math.max(v.lastIndexOf(","),v.lastIndexOf(";"),v.lastIndexOf("\n"));const prefix=cut>=0?v.slice(0,cut+1).replace(/[;\n]$/g,",")+" ":"";E.multi.value=prefix+m.part+", ";E.multiSuggest.hidden=true;state.mIndex=-1;E.multi.focus()}
function keyNav(e,box,type){const items=[...box.children];if(!items.length)return;let key=type==="single"?"sIndex":"mIndex";if(e.key==="ArrowDown"||e.key==="ArrowUp"){e.preventDefault();state[key]=(state[key]+(e.key==="ArrowDown"?1:-1)+items.length)%items.length;(type==="single"?updateSingleSuggestions:updateMultiSuggestions)()}else if(e.key==="Enter"&&state[key]>=0){e.preventDefault();type==="single"?(()=>{const m=matches(E.search.value)[state[key]];if(m)E.search.value=m.part;E.suggest.hidden=true;state.page=1;render()})():selectMulti(state[key])}else if(e.key==="Escape")box.hidden=true}
function applyMulti(){const parts=parseParts(E.multi.value);if(!parts.length){state.multiParts=null;E.multiSummary.textContent=""}else{const avail=new Set(state.rows.map(r=>norm(r.part))),found=parts.filter(p=>avail.has(p)),missing=parts.filter(p=>!avail.has(p));state.multiParts=new Set(parts);E.multiSummary.textContent=`Found ${found.length} of ${parts.length} part numbers${missing.length?`; not found: ${missing.join(", ")}`:""}`}state.page=1;render()}
async function sha(v){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")}async function auth(){if(!E.exportPw.value){E.exportStatus.textContent="Enter the export password.";return false}const ok=await sha(E.exportPw.value)===EXPORT_PASSWORD_HASH;E.exportStatus.textContent=ok?"Password accepted.":"Incorrect password.";return ok}
function matrix(){const rows=filtered(),locs=visibleLocations(rows);return[["PartNumber","Description",...locs,"Total"],...rows.map(r=>[r.part,r.desc,...locs.map(l=>num(r.quantities[l])||""),r.total])]}function download(b,n){const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}function cell(v){return`"${txt(v).replace(/"/g,'""')}"`}async function csv(){if(!await auth())return;download(new Blob(["\ufeff",matrix().map(r=>r.map(cell).join(",")).join("\r\n")],{type:"text/csv"}),"stock-export.csv")}async function excel(){if(!await auth())return;const esc=s=>txt(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");const rows=matrix().map((r,i)=>`<Row>${r.map((v,j)=>`<Cell><Data ss:Type="${i&&j>=2&&v!==""?"Number":"String"}">${esc(v)}</Data></Cell>`).join("")}</Row>`).join("");download(new Blob([`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Stock"><Table>${rows}</Table></Worksheet></Workbook>`],{type:"application/vnd.ms-excel"}),"stock-export.xls")}
E.search.oninput=()=>{state.sIndex=-1;state.page=1;render()};E.search.onkeydown=e=>keyNav(e,E.suggest,"single");E.multi.oninput=()=>{state.mIndex=-1;updateMultiSuggestions()};E.multi.onkeydown=e=>keyNav(e,E.multiSuggest,"multi");$("applyMulti").onclick=applyMulti;$("clearMulti").onclick=()=>{E.multi.value="";E.multiSummary.textContent="";state.multiParts=null;render()};$("clearSearch").onclick=()=>{E.search.value="";state.page=1;render()};$("pageSize").onchange=e=>{state.pageSize=num(e.target.value);state.page=1;render()};$("prevPage").onclick=()=>{state.page--;render()};$("nextPage").onclick=()=>{state.page++;render()};$("refreshButton").onclick=()=>if(E.search){E.search.value='';E.search.setAttribute('autocomplete','off');}state.page=1;loadData(true);$("exportToggle").onclick=e=>{e.stopPropagation();E.exportMenu.hidden=!E.exportMenu.hidden};$("exportCsv").onclick=csv;$("exportExcel").onclick=excel;document.onclick=e=>{if(!e.target.closest(".search-wrap"))E.suggest.hidden=true;if(!e.target.closest(".multi-wrap"))E.multiSuggest.hidden=true;if(!e.target.closest(".export-wrap"))E.exportMenu.hidden=true};loadData();setInterval(loadData,REFRESH_MS);